// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreSUS.Models.Data;

namespace NetCoreSUS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreSUS.Models.BusinessModels.ServiceHistory", b =>
                {
                    b.Property<Guid>("ServiceHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Lede");

                    b.Property<Guid>("ServiceId");

                    b.Property<Guid?>("SurveyId");

                    b.Property<string>("What");

                    b.Property<DateTime>("When");

                    b.HasKey("ServiceHistoryId");

                    b.HasIndex("SurveyId");

                    b.ToTable("ServiceHistory");
                });

            modelBuilder.Entity("NetCoreSUS.Models.BusinessModels.Survey", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("ServiceName");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("SurveyName");

                    b.HasKey("SurveyId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("NetCoreSUS.Models.BusinessModels.SurveyResponse", b =>
                {
                    b.Property<Guid>("SurveyResponseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Q1");

                    b.Property<int>("Q2");

                    b.Property<int>("Q3");

                    b.Property<int>("Q4");

                    b.Property<int>("Q5");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid>("SurveyId");

                    b.HasKey("SurveyResponseId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("NetCoreSUS.Models.BusinessModels.ServiceHistory", b =>
                {
                    b.HasOne("NetCoreSUS.Models.BusinessModels.Survey", "Survey")
                        .WithMany("ServiceHistory")
                        .HasForeignKey("SurveyId");
                });

            modelBuilder.Entity("NetCoreSUS.Models.BusinessModels.SurveyResponse", b =>
                {
                    b.HasOne("NetCoreSUS.Models.BusinessModels.Survey", "Survey")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
